/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;


import LastRun.src.utility.DoubleLinkedList;
import controller.action.Action;
import controller.action.stateMachineAction.GoBackAction;
import controller.action.stateMachineAction.GoToGameAction;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import utility.ImageUtil;

public class PetSelectionViewport extends Viewport {

    /***
     * Creates new form MenuViewport
     */
    
    public static void main(String[] args) {

        JFrame frame = new JFrame();
        frame.setSize(500, 500);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        PetSelectionViewport petSelectionView = new PetSelectionViewport();
        frame.add(petSelectionView);
        frame.setVisible(true);

    }
    
    DoubleLinkedList<OcupationCategory> ocupationList = new DoubleLinkedList();
    
    public enum OcupationCategory {
        
        SMASHER,
        SUMMONER,
        SNEAK;
    }
    
    public PetSelectionViewport() {
        initComponents();
        backgroundImage = new ImageIcon(ImageUtil.CHARACTER_SELECTION_BACKGROUND);
        addActionListeners();
        addAvatarOcupations();
    }
    
    public JButton getStartGameButton(){
        return startGameButton;
    }
    
    public JButton getCharacterButton(){
        return mainMenuButton;
    }
    
    private void addAvatarOcupations(){
        
        ocupationList.add(OcupationCategory.SMASHER);
        ocupationList.add(OcupationCategory.SNEAK);
        ocupationList.add(OcupationCategory.SUMMONER);
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
         g.drawImage(backgroundImage.getImage(), 0, 0, this.getWidth(), this.getHeight(), this);
    }
    
    private void paintAvatarOcupation(JPanel panel, Graphics g){
        Image image2 = null;
        switch (ocupationList.getData()){
        
            case SMASHER:
                image2 = ImageUtil.getImage( ImageUtil.MAIN_MENU_EXIT_BUTTON).getImage();
                break;
            case SUMMONER:
                image2 = ImageUtil.getImage( ImageUtil.MAIN_MENU_LOAD_BUTTON).getImage();
                break;
            default:
                image2 = ImageUtil.getImage( ImageUtil.CHARACTER_SELECTION_PET).getImage();
                break;
        }
        Image image = ImageUtil.getImage( ImageUtil.CHARACTER_SELECTION_PET, image2.getWidth(panel)*2/3, panel.getHeight()).getImage();
        g.drawImage( image , panel.getWidth()/2 - image.getWidth(panel)/2, 0, panel);
    }
    
    private final MouseListener changeOcupationAction = new MouseListener() {

        @Override
        public void mouseClicked(MouseEvent e) {
            
            Point location  = e.getLocationOnScreen();
            Point panelLocation = ocupationPanel.getLocation();
            
            // 1/3 Left of the panel
            if ( location.x <= ocupationPanel.getWidth()/3+panelLocation.x ){
                
                ocupationList.previous();
                ocupationPanel.repaint();
            }
            // 1/3 to the right
            else if (location.x >= ocupationPanel.getWidth()*2/3+panelLocation.x ){
                
                ocupationList.next();
                ocupationPanel.repaint();
            }
        }

        @Override
        public void mousePressed(MouseEvent e) {
            
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }
    };
    
    private void addActionListeners(){
        mainMenuButton.addActionListener(Action.getActionListener(new GoBackAction()));
        startGameButton.addActionListener(Action.getActionListener(new GoToGameAction()));
        ocupationPanel.addMouseListener(changeOcupationAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startGameButton = new javax.swing.JButton(){

            @Override
            public void paintComponent(Graphics g){
                Image image = ImageUtil.getImage( ImageUtil.CHARACTER_SELECTION_NEW_GAME_BUTTON,this.getWidth(), this.getHeight()).getImage();
                g.drawImage( image , 0, 0, this);
            }
        };
        mainMenuButton = new javax.swing.JButton(){

            @Override
            public void paintComponent(Graphics g){
                Image image = ImageUtil.getImage( ImageUtil.CHARACTER_SELECTION_MENU_BUTTON, this.getWidth(), this.getHeight()).getImage();
                g.drawImage( image , 0, 0, this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        ocupationPanel = new javax.swing.JPanel() {
            @Override
            public void paintComponent(Graphics g){

                paintAvatarOcupation(this,g);
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        avatarDescriptionTextArea = new javax.swing.JTextArea();
        avatarOcuppationNameLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel(){

            @Override
            public void paintComponent(Graphics g){
                Image image = ImageUtil.getImage( ImageUtil.CHARACTER_SELECTION_PET,this.getWidth()/3,this.getHeight()).getImage();
                g.drawImage( image , this.getWidth()/2 - image.getWidth(this)/2, 0, this);
            }
        };
        jPanel4 = new javax.swing.JPanel();
        avatarNickNameLabel = new javax.swing.JLabel();
        avatarNickNameTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(202, 175, 149));

        startGameButton.setText("Start Game");
        startGameButton.setPreferredSize(new java.awt.Dimension(148, 65));

        mainMenuButton.setText("Menu");
        mainMenuButton.setPreferredSize(new java.awt.Dimension(148, 65));

        jPanel1.setOpaque(false);

        ocupationPanel.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout ocupationPanelLayout = new javax.swing.GroupLayout(ocupationPanel);
        ocupationPanel.setLayout(ocupationPanelLayout);
        ocupationPanelLayout.setHorizontalGroup(
            ocupationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        ocupationPanelLayout.setVerticalGroup(
            ocupationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setOpaque(false);

        avatarDescriptionTextArea.setBackground(new java.awt.Color(0, 51, 51));
        avatarDescriptionTextArea.setColumns(20);
        avatarDescriptionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        avatarDescriptionTextArea.setRows(5);
        avatarDescriptionTextArea.setText("\tAvatar description goes here");
        avatarDescriptionTextArea.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(163, 43, 43)));
        avatarDescriptionTextArea.setMargin(new java.awt.Insets(0, 0, 0, 0));
        avatarDescriptionTextArea.setMaximumSize(new java.awt.Dimension(853, 2147483647));
        jScrollPane1.setViewportView(avatarDescriptionTextArea);

        avatarOcuppationNameLabel.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        avatarOcuppationNameLabel.setForeground(new java.awt.Color(240, 240, 240));
        avatarOcuppationNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarOcuppationNameLabel.setText("Hello");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ocupationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avatarOcuppationNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addGap(196, 196, 196))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ocupationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(avatarOcuppationNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel4.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel4.setOpaque(false);

        avatarNickNameLabel.setFont(new java.awt.Font("Yu Mincho", 2, 36)); // NOI18N
        avatarNickNameLabel.setForeground(new java.awt.Color(240, 240, 240));
        avatarNickNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarNickNameLabel.setText("Nickname:");

        avatarNickNameTextField.setFont(new java.awt.Font("Yu Mincho", 3, 36)); // NOI18N
        avatarNickNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        avatarNickNameTextField.setText("Marie");
        avatarNickNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 3, new java.awt.Color(163, 43, 43)));
        avatarNickNameTextField.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatarNickNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avatarNickNameTextField)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avatarNickNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avatarNickNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(startGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea avatarDescriptionTextArea;
    private javax.swing.JLabel avatarNickNameLabel;
    private javax.swing.JTextField avatarNickNameTextField;
    private javax.swing.JLabel avatarOcuppationNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JPanel ocupationPanel;
    private javax.swing.JButton startGameButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void render() {
        this.revalidate();
    }

    
}
