/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.viewport;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.ConcurrentModificationException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import model.enums.StatsCategory;
import model.stat.Stats;
import utility.ImageUtil;

/**
 *
 * @author Carlos
 */
public class StatisticsViewport extends Viewport {

    /**
     * Creates new form StatisticsViewport
     */
    ArrayList<String> stats = new ArrayList<>();
    public StatisticsViewport(Stats stats) {
        initComponents();
        paintStatsIcons();
         try{
            stats.registerView(this);
         }
         catch(ConcurrentModificationException ex){}
    }
    
    public void paintComponent(Graphics g) {
		super.paintComponent(g);
		drawStats(g);
    }
    
    private void drawStats(Graphics g) {
	
    }
    
    private void paintStatsIcons(){
        Image image = null;
        ImageIcon imageIcon = null;
        
        image = ImageUtil.getImage(ImageUtil.STATS_LIVES_LEFT_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        livesLeftButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_DEFENSIVE_RATING_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        defensiveRatingButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_ARMOR_RATING_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        armorRatingButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_ARMOR_RATING_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        armorRatingButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_EQUIPPED_WEAPON_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        equippedWeaponButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_ARMOR_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        equippedArmorButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_MANA_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        manaButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_AGILITY_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        agilityButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_LEVEL_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        levelButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_MOVEMENT_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        movementButton.setIcon( imageIcon );
        
        image = ImageUtil.getImage(ImageUtil.STATS_EXPERIENCE_DECAL).getImage();
        imageIcon = new ImageIcon(image);
        experienceButton.setIcon( imageIcon );
        
    }
    
    public void receive(ArrayList<Integer> stats, ArrayList<StatsCategory> categories) {
		
        for ( int i = 0; i < stats.size(); i++){
            
            switch(categories.get(i)){
            
                case LIVES_LEFT:
                    break;
                case MANA:
                    break;
                case LIFE:
                    break;
                case STRENGTH:
                    break;
                case INTELLECT:
                    break;
                case HARDINESS:
                    break;
                case EXPERIENCE:
                    break;
                case MOVEMENT:
                    break;
                case EQUIPPED_ARMOR:
                    break;
                case EQUIPPED_WEAPON:
                    break;
                case ARMOR_RATING:
                    break;
                case DEFENSIVE_RATING:
                    break;
                case OFFENSIVE_RATING:
                    break;
                case LEVEL:
                    break;
                case AGILITY:
                    break;
            
            }
        }
     }
    
     @Override
	public void render() {
	
      }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agilityPanel4 = new javax.swing.JPanel();
        skillsPanel = new javax.swing.JPanel();
        equippedArmorButton = new javax.swing.JButton();
        equippedWeaponButton = new javax.swing.JButton();
        equipedArmorPanel = new javax.swing.JPanel();
        equippedWeaponPanel = new javax.swing.JPanel();
        levePanel = new javax.swing.JPanel();
        levelButton = new javax.swing.JButton();
        movementButton = new javax.swing.JButton();
        movementJPanel = new javax.swing.JPanel();
        levelPanel = new javax.swing.JPanel();
        progressBarPanel = new javax.swing.JPanel();
        lifeButton = new javax.swing.JButton();
        livesLeftButton = new javax.swing.JButton();
        manaButton = new javax.swing.JButton();
        livesLeftProgressBar = new javax.swing.JProgressBar();
        lifeProgressBar = new javax.swing.JProgressBar();
        manaProgressBar = new javax.swing.JProgressBar();
        skillsPanel1 = new javax.swing.JPanel();
        hardinessButton = new javax.swing.JButton();
        intellectButton = new javax.swing.JButton();
        hardinessPanel = new javax.swing.JPanel();
        intellectPanel = new javax.swing.JPanel();
        skillsPanel2 = new javax.swing.JPanel();
        agilityButton = new javax.swing.JButton();
        experienceButton = new javax.swing.JButton();
        agilityPanel = new javax.swing.JPanel();
        experiencePanel = new javax.swing.JPanel();
        skillsPanel3 = new javax.swing.JPanel();
        armorRatingButton = new javax.swing.JButton();
        defensiveRatingButton = new javax.swing.JButton();
        agilityPanel2 = new javax.swing.JPanel();
        somethingelse = new javax.swing.JPanel();

        javax.swing.GroupLayout agilityPanel4Layout = new javax.swing.GroupLayout(agilityPanel4);
        agilityPanel4.setLayout(agilityPanel4Layout);
        agilityPanel4Layout.setHorizontalGroup(
            agilityPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        agilityPanel4Layout.setVerticalGroup(
            agilityPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 153, 0));

        skillsPanel.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout equipedArmorPanelLayout = new javax.swing.GroupLayout(equipedArmorPanel);
        equipedArmorPanel.setLayout(equipedArmorPanelLayout);
        equipedArmorPanelLayout.setHorizontalGroup(
            equipedArmorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        equipedArmorPanelLayout.setVerticalGroup(
            equipedArmorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout equippedWeaponPanelLayout = new javax.swing.GroupLayout(equippedWeaponPanel);
        equippedWeaponPanel.setLayout(equippedWeaponPanelLayout);
        equippedWeaponPanelLayout.setHorizontalGroup(
            equippedWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        equippedWeaponPanelLayout.setVerticalGroup(
            equippedWeaponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout skillsPanelLayout = new javax.swing.GroupLayout(skillsPanel);
        skillsPanel.setLayout(skillsPanelLayout);
        skillsPanelLayout.setHorizontalGroup(
            skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanelLayout.createSequentialGroup()
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(equippedArmorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(equippedWeaponButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equippedWeaponPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(equipedArmorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        skillsPanelLayout.setVerticalGroup(
            skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanelLayout.createSequentialGroup()
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equippedArmorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(equipedArmorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equippedWeaponButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(equippedWeaponPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        levePanel.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout movementJPanelLayout = new javax.swing.GroupLayout(movementJPanel);
        movementJPanel.setLayout(movementJPanelLayout);
        movementJPanelLayout.setHorizontalGroup(
            movementJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        movementJPanelLayout.setVerticalGroup(
            movementJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout levelPanelLayout = new javax.swing.GroupLayout(levelPanel);
        levelPanel.setLayout(levelPanelLayout);
        levelPanelLayout.setHorizontalGroup(
            levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        levelPanelLayout.setVerticalGroup(
            levelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout levePanelLayout = new javax.swing.GroupLayout(levePanel);
        levePanel.setLayout(levePanelLayout);
        levePanelLayout.setHorizontalGroup(
            levePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levePanelLayout.createSequentialGroup()
                .addComponent(levelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movementJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        levePanelLayout.setVerticalGroup(
            levePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movementButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
            .addComponent(movementJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(levelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(levelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        progressBarPanel.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout progressBarPanelLayout = new javax.swing.GroupLayout(progressBarPanel);
        progressBarPanel.setLayout(progressBarPanelLayout);
        progressBarPanelLayout.setHorizontalGroup(
            progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressBarPanelLayout.createSequentialGroup()
                .addGroup(progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(livesLeftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lifeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(livesLeftProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lifeProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manaProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        progressBarPanelLayout.setVerticalGroup(
            progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressBarPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(livesLeftProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(livesLeftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lifeProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(lifeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(progressBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manaProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        skillsPanel1.setBackground(new java.awt.Color(51, 0, 51));

        intellectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intellectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hardinessPanelLayout = new javax.swing.GroupLayout(hardinessPanel);
        hardinessPanel.setLayout(hardinessPanelLayout);
        hardinessPanelLayout.setHorizontalGroup(
            hardinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        hardinessPanelLayout.setVerticalGroup(
            hardinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout intellectPanelLayout = new javax.swing.GroupLayout(intellectPanel);
        intellectPanel.setLayout(intellectPanelLayout);
        intellectPanelLayout.setHorizontalGroup(
            intellectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        intellectPanelLayout.setVerticalGroup(
            intellectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout skillsPanel1Layout = new javax.swing.GroupLayout(skillsPanel1);
        skillsPanel1.setLayout(skillsPanel1Layout);
        skillsPanel1Layout.setHorizontalGroup(
            skillsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanel1Layout.createSequentialGroup()
                .addGroup(skillsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(intellectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(hardinessButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skillsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hardinessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intellectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        skillsPanel1Layout.setVerticalGroup(
            skillsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanel1Layout.createSequentialGroup()
                .addComponent(hardinessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intellectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(skillsPanel1Layout.createSequentialGroup()
                .addComponent(hardinessButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intellectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        skillsPanel2.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout agilityPanelLayout = new javax.swing.GroupLayout(agilityPanel);
        agilityPanel.setLayout(agilityPanelLayout);
        agilityPanelLayout.setHorizontalGroup(
            agilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        agilityPanelLayout.setVerticalGroup(
            agilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout experiencePanelLayout = new javax.swing.GroupLayout(experiencePanel);
        experiencePanel.setLayout(experiencePanelLayout);
        experiencePanelLayout.setHorizontalGroup(
            experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        experiencePanelLayout.setVerticalGroup(
            experiencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout skillsPanel2Layout = new javax.swing.GroupLayout(skillsPanel2);
        skillsPanel2.setLayout(skillsPanel2Layout);
        skillsPanel2Layout.setHorizontalGroup(
            skillsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanel2Layout.createSequentialGroup()
                .addGroup(skillsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(agilityButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(experienceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skillsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(experiencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agilityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        skillsPanel2Layout.setVerticalGroup(
            skillsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanel2Layout.createSequentialGroup()
                .addGroup(skillsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agilityButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(agilityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skillsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(experienceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(experiencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        skillsPanel3.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout agilityPanel2Layout = new javax.swing.GroupLayout(agilityPanel2);
        agilityPanel2.setLayout(agilityPanel2Layout);
        agilityPanel2Layout.setHorizontalGroup(
            agilityPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        agilityPanel2Layout.setVerticalGroup(
            agilityPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout somethingelseLayout = new javax.swing.GroupLayout(somethingelse);
        somethingelse.setLayout(somethingelseLayout);
        somethingelseLayout.setHorizontalGroup(
            somethingelseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        somethingelseLayout.setVerticalGroup(
            somethingelseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout skillsPanel3Layout = new javax.swing.GroupLayout(skillsPanel3);
        skillsPanel3.setLayout(skillsPanel3Layout);
        skillsPanel3Layout.setHorizontalGroup(
            skillsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanel3Layout.createSequentialGroup()
                .addGroup(skillsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(armorRatingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(defensiveRatingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skillsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agilityPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(somethingelse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        skillsPanel3Layout.setVerticalGroup(
            skillsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanel3Layout.createSequentialGroup()
                .addGroup(skillsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(armorRatingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(agilityPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(skillsPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(defensiveRatingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(somethingelse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(levePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skillsPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skillsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(skillsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(skillsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skillsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(skillsPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(skillsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(skillsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void intellectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intellectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intellectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agilityButton;
    private javax.swing.JPanel agilityPanel;
    private javax.swing.JPanel agilityPanel2;
    private javax.swing.JPanel agilityPanel4;
    private javax.swing.JButton armorRatingButton;
    private javax.swing.JButton defensiveRatingButton;
    private javax.swing.JPanel equipedArmorPanel;
    private javax.swing.JButton equippedArmorButton;
    private javax.swing.JButton equippedWeaponButton;
    private javax.swing.JPanel equippedWeaponPanel;
    private javax.swing.JButton experienceButton;
    private javax.swing.JPanel experiencePanel;
    private javax.swing.JButton hardinessButton;
    private javax.swing.JPanel hardinessPanel;
    private javax.swing.JButton intellectButton;
    private javax.swing.JPanel intellectPanel;
    private javax.swing.JPanel levePanel;
    private javax.swing.JButton levelButton;
    private javax.swing.JPanel levelPanel;
    private javax.swing.JButton lifeButton;
    private javax.swing.JProgressBar lifeProgressBar;
    private javax.swing.JButton livesLeftButton;
    private javax.swing.JProgressBar livesLeftProgressBar;
    private javax.swing.JButton manaButton;
    private javax.swing.JProgressBar manaProgressBar;
    private javax.swing.JButton movementButton;
    private javax.swing.JPanel movementJPanel;
    private javax.swing.JPanel progressBarPanel;
    private javax.swing.JPanel skillsPanel;
    private javax.swing.JPanel skillsPanel1;
    private javax.swing.JPanel skillsPanel2;
    private javax.swing.JPanel skillsPanel3;
    private javax.swing.JPanel somethingelse;
    // End of variables declaration//GEN-END:variables
}
